### ISSUE TITLE
How to further specify the ActivityStreams semantics

### ISSUE THREAD

**Issue by mielvds** [MellonScholarlyCommunication/spec-notifications#1]
Last meeting I promised to do some investigation about the approach the Core Notify project is taking wrt applying Activity Streams. 
Core Notify uses a very limited set of AS activity types `as:Offer`, `as:Undo`, `as:Accept`, `as:Reject`, and `as:Announce`. An [additional set of types](https://notify.coar-repositories.org/vocabularies/notify/) indicates the more specific intention of the activity: 

- ReviewRequest (http://purl.org/coar/notify_vocabulary/ReviewRequest )
- ReviewSuccess (http://purl.org/coar/notify_vocabulary/ReviewSuccess )
- ReviewFailure (http://purl.org/coar/notify_vocabulary/ReviewFailure )
- EndorsementRequest (http://purl.org/coar/notify_vocabulary/EndorsementRequest )
- EndorsementSuccess (http://purl.org/coar/notify_vocabulary/EndorsementSuccess )
- EndorsementFailure (http://purl.org/coar/notify_vocabulary/EndorsementFailure )
- IngestRequest (http://purl.org/coar/notify_vocabulary/IngestRequest )
- IngestSuccess (http://purl.org/coar/notify_vocabulary/IngestSuccess )

ActivityStreams is more or less used as a base structure, where the real interoperability is achieved by implementing the vocabulary above. If we align this work to this practice, it means that the set of AS types is defined in the shared specs and the additional vocabulary is defined by the use cases, like in this case scholarly communication. This could work.

Another approach (which is what I was on until now) would be to fix the interpretation of AS in the context of this project and therefore aim to reuse as much AS types as possible and avoid additional curstom terms for activities.

Some thoughts:
- The scope of Core notify limited to reviewing, endorsing and ingesting, but in a general decentralized network with actors and services, there might be more. Do we need to define a more extensive set of AS types (as in https://github.com/MellonScholarlyCommunication/spec-orchestrator/issues/8)? And if so, what would we use it for? 
- What level of specificity is best? You could 'Announce' everything, but how does that bring clarity about lifecycle events? (`as:Create` vs event 'artefact was created'). What is the relation between the core-notify notifications and the events in the event log?
- How 'open-ended' and generic should we make the communication in this project? I believe: very, but usable. Using announce just tells the service there is some artefact. Offer tells the service the same, but with a clear intent. Not absolute guarentees in both situations that the service will do what you want them to do.
- What is in practice the difference between telling a service that you 'created' an artifact and 'announcing' its existence? 

Still thinking about this, but @phochste @Dexagod @JWerbrouck interested in your thoughts.

**Comment by mielvds** [comment]
A quick summarization of the recent discussion.
The approaches between COAR notify and what was originally proposed in the ResearcherPod proposal are different in a sense that the `activity` has a different intent and that the `object` plays a different role. You could say that COAR notify is like RPC (the type is used as an action, eg. ReviewRequest), while notifications were originally envisioned as resource-oriented. 
Let me summarize in two possible models:

**Model A: action-oriented**

A notification is either about 1) requesting a service from a Service Hub; or 2) responding to such requests. For example, a researcher can offer a ReviewRequest and the reviewing service can reply with ReviewSuccess or ReviewFailure. Hence, there is dependency / referral between notifications. Activities are about services, not about artefacts. 

_Activity:_ the service requested by the sender (eg. Offer = I'm requesting some action from X)
_Object:_ an optional artefact related to the service


**Model B: artefact-oriented**

A notification only disseminates an event related to an artefact; it does not specify what service caused the event to occur. For example, a researcher can send an Offer notification to a reviewing service once or more. After the service has been completed, the reviewing service can send a Reviewed notification. Hence, there is no dependency or referral between notifications. Activities are about artefacts, not about services.

_Activity:_ a lifecycle event (eg. Offer = artefact was offered to X)
_Object:_ a mandatory artefact that is the subject of the lifecycle event

**Comment by phochste** [comment]
I'm certainly in line with Model-B, if we have the flexibility what will call an artefact.

If Alice sends an _offer_ O(A1) about her artefact _A1_ to Bob , then 

- Activity: O(A1)
- Artefact: A1

If Bob sends an _accept_ (or _reject_) about Alice's offer O1 to Alice, then:

- Activity: Accept A(O(A1)) | Reject R(O(A1))
- Artefact: O(A1)

The point is that Bob accepts or rejects the offer on the artefact, not the artefact. Alice needs to infer from O(A1) that it is about her artefact. Btw, in COAR they don't use the `object` but `inReplyTo` for these types of artefacts.

About the previous question on the difference between an Announce and Create , this has to do with timing of activities. E.g.

- Alice uploads a article A1 ..this could trigger a create event : C(A1)
- Alice works on the article A1 for some weeks in private and is now ready to release it into public ..this could trigger an announce event: A(A1)

**Comment by mielvds** [comment]
> I'm certainly in line with Model-B, if we have the flexibility what will call an artefact.

It boils down to whether if an activity is allowed to be an artefact or not. The way Model-B was envisioned, the answer is no, but maybe it shouldn't be.

> 
> If Alice sends an _offer_ O(A1) about her artefact _A1_ to Bob , then
> 
>     * Activity: O(A1)
> 
>     * Artefact: A1
> 
> 
> If Bob sends an _accept_ (or _reject_) about Alice's offer O1 to Alice, then:
> 
>     * Activity: Accept A(O(A1)) | Reject R(O(A1))
> 
>     * Artefact: O(A1)
> 
> 
> The point is that Bob accepts or rejects the offer on the artefact, not the artefact. Alice needs to infer from O(A1) that it is about her artefact. 

Yes, and I think that's a lean way of looking at it. I just wonder: 
- if you are contacting a Review/Certification Service Hub, why would you need to specify the intent (= review)? 
- If you send `O(A1)` 10 times; what should `A(O(A1))` look like?

> Btw, in COAR they don't use the `object` but `inReplyTo` for these types of artefacts.

That makes sense if you have a request-reply paradigm in you activities. Model-B is about keeping the activities as generic as possible. 

> 
> About the previous question on the difference between an Announce and Create , this has to do with timing of activities. E.g.
> 
>     * Alice uploads a article A1 ..this could trigger a create event : C(A1)
> 
>     * Alice works on the article A1 for some weeks in private and is now ready to release it into public ..this could trigger an announce event: A(A1)

+1

**Comment by phochste** [comment]
@mielvds in light of your discussion of this week about Model A/B and less or more request/answer is this also related to the business cases for erfgoed? In [Subscribing to a Topic](https://erfgoedpod.github.io/usecases/#-bp8-subscribing-to-a-topic) there is also a request (Subscribe) and answer (isSubscribedTo) pattern which mimics somewhat the Offer/Accept communication in COAR. Wouldn't lead the this communication pattern to the same kind of notification style?

**Comment by mielvds** [comment]
Depends on the perspective we take. It's "Actor A requests subscription / Service Hub: Actor A is subscribed" vs. "Actor A requests subscription / Service Hub: I accept Actor A's request for subscription" But indeed, the Offer/Accept communication makes sense here, but it would definitely be something specific to the Cultural Heritage use case.

**Comment by mielvds** [comment]
Thought: perhaps we write Model B as a formative pattern and the Model A as an informative pattern for "communication requiring acknowledgement"

**Comment by hvdsomp** [comment]
Somehow it seems to me that COAR Notify has circumvented/solved the Model A versus Model B thing by using Model B for notifications pertaining to artefacts (announce, offer) and inReplyTo for communication related to prior notifications. Is this not an acceptable pattern in general?
