### ISSUE TITLE
Do we need a third class of Activities?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-notifications#8]
In the spec section 4 we describe now 2 classes of events:

1. Disseminating lifecycle aspects
2. Requesting services

These 2 classes describe some sort of a state change for the artefact.

In the Mellon project there is also a class of events that don't lead to a state change and are more "interaction events". E.g. a pod receives a notification that a dataset is cited, annotated.. 

Most probably these "interaction events" use the same notifications as currently in "Requesting services" . 

There are also notifications that are out of scope for this project: e.g. herbert has an example "a notification which lists all the places where a paper has been cited..the result of some sort of aggregation"/

**Comment by mielvds** [comment]
I wouldn't call them classes of events, but rather groups according to purpose. AFAIK there is no such thing as an interaction event in the proposal. There are, however, `interaction artefacts` who have, just like `artefacts`, lifecycle events that need to be disseminated. `Interaction artefacts` can be annotations, reviews, comments, likes, etc. and (always?) have some relation to an `artefact`.

This discussion of course depends on the discussion we had about `the two models`. I'll document this discussion in #1.

> There are also notifications that are out of scope for this project: e.g. herbert has an example "a notification which lists all the places where a paper has been cited..the result of some sort of aggregation"/

This could be an additional service on top of the collector. But I don't think this is any different from announcing the existence of an artefact.

**Comment by phochste** [comment]
This has been superseded in the current version of the spec where there it is possible to Announce all kinds of things for artifacts without first requesting a service. E.g. our [publication](https://arxiv.org/pdf/2208.00665.pdf) provides a whole publication/research data link announcement without requesting a service and without related to a disseminating lifecycle event.
